import { Category, CategoryId, Challenge, PhotoTerm } from './types';

// Ordered as a learning path: light and composition matter most, named gear and film looks come later.
export const CATEGORIES: Category[] = [
  {
    id: 'lighting',
    label: 'Light',
    title: 'Light',
    description: 'Light sets the mood more than anything else. Start with its quality (hard or soft), its direction, and the time of day, then learn the named studio setups.',
  },
  {
    id: 'composition',
    label: 'Composition',
    title: 'Composition',
    description: 'Where things sit inside the frame. Good composition leads the eye to the subject and gives the picture balance or tension.',
  },
  {
    id: 'framing',
    label: 'Shot size',
    title: 'Shot size',
    description: 'How much of the subject the frame shows, from a single eye to a whole landscape. Tighter shots feel more intimate; wider shots show context.',
  },
  {
    id: 'angles',
    label: 'Camera angle',
    title: 'Camera angle',
    description: 'Where the camera sits relative to the subject. Height and tilt change how powerful, small, or unsettled the subject feels.',
  },
  {
    id: 'lenses',
    label: 'Lenses',
    title: 'Lenses & focal length',
    description: 'Focal length sets how wide the view is and how the background relates to the subject. Wide lenses exaggerate depth; long lenses flatten it.',
  },
  {
    id: 'exposure',
    label: 'Exposure & focus',
    title: 'Exposure & focus',
    description: 'Aperture, shutter speed, and ISO control brightness, and each has a side effect you can see: background blur, motion blur, or grain.',
  },
  {
    id: 'color-film',
    label: 'Color & film',
    title: 'Color & film looks',
    description: 'Color temperature and grading set the emotional tone. Film stocks are shorthand for a whole look: their colors, contrast, and grain.',
  },
  {
    id: 'movements',
    label: 'Movement',
    title: 'Camera movement (video)',
    description: 'For video prompts only: how the camera moves during the shot. Movement guides attention and adds energy or tension.',
  },
];

export const CATEGORY_BY_ID: Record<CategoryId, Category> = Object.fromEntries(
  CATEGORIES.map((c) => [c.id, c])
) as Record<CategoryId, Category>;

export const PHOTOGRAPHY_TERMS: PhotoTerm[] = [
  // ---------------- Light ----------------
  {
    id: 'light-soft',
    name: 'Soft Light',
    category: 'lighting',
    level: 'fundamental',
    definition: 'Light from a source that is large compared with the subject, such as an overcast sky, a big window, or a diffused softbox. It wraps around shapes.',
    lookFor: 'Shadows fade gradually with blurry edges. Skin looks smooth and texture is gentle.',
    phrase: 'lit by soft, diffused light that wraps around the subject with gentle, gradual shadows',
    keywords: 'soft diffused light, gentle shadows',
    videoPhrase: 'soft diffused light with gentle shadows',
    tip: 'Flattering for portraits, food, and products. Pair with a direction ("soft light from the left") so the image still has shape.',
    insight: 'Softness depends on the size of the light relative to the subject, not its brightness. The sun is huge but so far away that it acts as a small, hard source; clouds turn the whole sky into a giant soft one.',
    exampleQuery: 'soft light portrait overcast',
  },
  {
    id: 'light-hard',
    name: 'Hard Light',
    category: 'lighting',
    level: 'fundamental',
    definition: 'Light from a small or distant source, such as direct midday sun, a bare bulb, or a spotlight.',
    lookFor: 'Crisp, sharp-edged shadows and strong contrast. Surface texture stands out.',
    phrase: 'lit by hard, direct light that casts crisp, sharp-edged shadows',
    keywords: 'hard direct light, crisp shadows, high contrast',
    videoPhrase: 'hard direct light casting crisp shadows',
    tip: 'Use for drama, graphic shadows, fashion, and harsh environments like deserts. Describe where the shadow falls to make it convincing.',
    insight: 'Hard light is not "bad" light. Film noir, summer street photography, and fashion editorials all use it on purpose for its bold shapes.',
    exampleQuery: 'hard light shadow photography',
  },
  {
    id: 'light-golden-hour',
    name: 'Golden Hour',
    category: 'lighting',
    level: 'fundamental',
    definition: 'The period shortly after sunrise and before sunset when the sun is low in the sky.',
    lookFor: 'Warm orange-gold light, long soft shadows, and glowing edges when the sun is behind the subject.',
    phrase: 'during golden hour, with low, warm sunlight raking across the scene and long soft shadows',
    keywords: 'golden hour, warm low sun, long shadows',
    videoPhrase: 'warm golden-hour sunlight, low on the horizon',
    tip: 'The easiest way to make outdoor scenes feel warm and cinematic. Put the sun behind the subject for a glowing outline.',
    insight: 'When the sun is low its light travels through more atmosphere, which scatters blue light away. That leaves warmer light, and the low angle makes shadows long.',
    exampleQuery: 'golden hour portrait backlit',
  },
  {
    id: 'light-blue-hour',
    name: 'Blue Hour',
    category: 'lighting',
    level: 'intermediate',
    definition: 'The short twilight just before sunrise or just after sunset, when the sun is below the horizon.',
    lookFor: 'A deep blue sky, soft even light with almost no shadows, and warm city lights standing out against the blue.',
    phrase: 'at blue hour, under a deep blue twilight sky, with warm artificial lights glowing against the cool ambient light',
    keywords: 'blue hour, twilight, deep blue sky, city lights',
    videoPhrase: 'blue-hour twilight with warm lights coming on',
    tip: 'Great for cityscapes and moody exteriors. The warm/cool contrast between streetlights and sky is the signature look.',
    insight: 'With the sun below the horizon, only scattered skylight remains, which is strongly blue. It lasts roughly 20 to 40 minutes depending on your latitude.',
    exampleQuery: 'blue hour cityscape',
  },
  {
    id: 'light-side-window',
    name: 'Side Light (Window Light)',
    category: 'lighting',
    level: 'fundamental',
    definition: 'Light coming from one side of the subject, classically from a nearby window.',
    lookFor: 'One side of the face or object is bright and the other falls into shadow, which shows its shape and texture.',
    phrase: 'lit by soft window light from one side, so one side is bright and the other falls gently into shadow',
    keywords: 'side lighting, window light, split light',
    videoPhrase: 'soft window light from one side',
    tip: 'The simplest way to add depth. Say which side the light comes from, and whether the window is large (soft) or small (hard).',
    insight: 'Front light flattens shapes because shadows fall behind the subject. Moving the light to the side puts shadows on the subject, and those shadows are what show form.',
    exampleQuery: 'window light portrait side',
  },
  {
    id: 'lighting-three-point',
    name: 'Three-Point Lighting',
    category: 'lighting',
    level: 'intermediate',
    definition: 'The standard studio setup: a key light (the main light), a fill light (softens the key\'s shadows), and a back light (separates the subject from the background).',
    lookFor: 'A well-shaped face with visible but gentle shadows, and a thin bright outline on hair and shoulders.',
    phrase: 'lit with classic three-point lighting: a key light to one side, a soft fill opposite, and a back light outlining the hair and shoulders',
    keywords: 'three-point lighting, key light, fill light, backlight',
    videoPhrase: 'interview-style three-point lighting',
    tip: 'Use for clean, professional portraits, interviews, and product shots. It looks polished rather than moody.',
    insight: 'The brightness difference between key and fill (the lighting ratio) sets the mood: close to equal feels open and friendly, a big difference feels dramatic.',
    exampleQuery: 'three point lighting portrait',
  },
  {
    id: 'lighting-rembrandt',
    name: 'Rembrandt Lighting',
    category: 'lighting',
    level: 'intermediate',
    definition: 'A portrait setup where the key light sits high and roughly 45° to one side, so the nose\'s shadow meets the cheek shadow on the far side of the face.',
    lookFor: 'A small, bright triangle of light on the shadowed cheek, under the eye. The rest of that side stays dark.',
    phrase: 'lit with Rembrandt lighting: a single key light high and to one side, leaving a small triangle of light on the shadowed cheek',
    keywords: 'Rembrandt lighting, triangle of light on cheek, moody portrait',
    videoPhrase: 'Rembrandt-lit portrait with a triangle of light on the shadowed cheek',
    tip: 'A shortcut to a classic, painterly portrait. Mention the triangle on the cheek; models reproduce it more reliably when described.',
    insight: 'Named after the painter Rembrandt van Rijn, whose self-portraits often show this pattern. Keep fill light low or the triangle disappears.',
    exampleQuery: 'Rembrandt lighting portrait triangle',
  },
  {
    id: 'lighting-highkey',
    name: 'High-Key Lighting',
    category: 'lighting',
    level: 'intermediate',
    definition: 'A bright, low-contrast style where fill and background lights keep shadows light and small.',
    lookFor: 'Mostly bright tones, a light or white background, and very few dark areas.',
    phrase: 'in bright high-key lighting, with a clean white background, minimal shadows, and low contrast',
    keywords: 'high-key lighting, bright, white background, low contrast',
    videoPhrase: 'bright, even high-key lighting',
    tip: 'Use for upbeat, clean, or airy images: beauty, commercials, product shots, and friendly portraits.',
    insight: 'It works by lowering the lighting ratio (key close to fill, often around 2:1) and lighting the background too. Sitcoms and many ads use it because it reads as cheerful.',
    exampleQuery: 'high key portrait photography',
  },
  {
    id: 'lighting-lowkey',
    name: 'Low-Key Lighting (Chiaroscuro)',
    category: 'lighting',
    level: 'intermediate',
    definition: 'A dark, high-contrast style dominated by shadow, usually one strong light with little or no fill. "Chiaroscuro" is the painting term for this strong light-dark contrast.',
    lookFor: 'Most of the frame is dark; only parts of the subject catch the light.',
    phrase: 'in dramatic low-key lighting, a single light source carving the subject out of deep shadow',
    keywords: 'low-key lighting, chiaroscuro, deep shadows, single light source',
    videoPhrase: 'low-key lighting with deep shadows and a single hard source',
    tip: 'Use for thrillers, noir, mystery, and intense portraits. Say what the light falls on so the model knows what to reveal.',
    insight: 'Low-key uses a high lighting ratio (8:1 or more). The drama comes from what you hide as much as what you show.',
    exampleQuery: 'low key portrait chiaroscuro',
  },
  {
    id: 'lighting-rim-edge',
    name: 'Rim Light (Backlight)',
    category: 'lighting',
    level: 'intermediate',
    definition: 'A light behind the subject, aimed toward the camera, that outlines the edges of the subject.',
    lookFor: 'A bright glowing outline around hair, shoulders, or the object\'s edge, separating it from a darker background.',
    phrase: 'with a strong rim light from behind, tracing a bright outline around the subject against a dark background',
    keywords: 'rim light, backlit, glowing edges, silhouette',
    videoPhrase: 'strong backlight tracing a glowing outline around the subject',
    tip: 'Great for silhouettes, athletes, smoke, rain, and making dark hair or clothing stand out from a dark background.',
    insight: 'Close cousin of the hair light, which sits above and behind the subject. With no front light at all, a rim light gives you a silhouette.',
    exampleQuery: 'rim light portrait dark background',
  },

  // ---------------- Composition ----------------
  {
    id: 'comp-rule-of-thirds',
    name: 'Rule of Thirds',
    category: 'composition',
    level: 'fundamental',
    definition: 'Imagine two horizontal and two vertical lines dividing the frame into nine equal parts, and place the subject on a line or where two lines cross.',
    lookFor: 'The subject sits off-center, with the horizon on the upper or lower third rather than through the middle.',
    phrase: 'composed with the rule of thirds, the subject placed off-center on the left third of the frame',
    keywords: 'rule of thirds, off-center subject',
    videoPhrase: 'subject framed off-center on the rule of thirds',
    tip: 'The easiest way to make a picture feel less static. Say which third the subject sits in, and where the horizon falls.',
    insight: 'It is a guideline, not a law. Off-center placement creates space for the eye to travel, which usually feels more natural than dead-center.',
    exampleQuery: 'rule of thirds photography',
  },
  {
    id: 'comp-leading-lines',
    name: 'Leading Lines',
    category: 'composition',
    level: 'fundamental',
    definition: 'Lines in the scene, such as roads, rails, rivers, or walls, that draw the viewer\'s eye toward the subject.',
    lookFor: 'Lines that start near the edges or foreground and converge on the subject.',
    phrase: 'with strong leading lines in the scene converging from the foreground toward the subject',
    keywords: 'leading lines, converging lines, depth',
    videoPhrase: 'leading lines drawing the eye toward the subject',
    tip: 'Name the actual lines in your scene (a pier, a corridor, tram tracks). Combine with a wide lens for extra depth.',
    insight: 'Our eyes follow edges. Lines that converge also create a strong sense of depth in a flat image.',
    exampleQuery: 'leading lines photography',
  },
  {
    id: 'comp-negative-space',
    name: 'Negative Space',
    category: 'composition',
    level: 'fundamental',
    definition: 'Large, mostly empty areas around the subject: plain sky, water, a wall, or darkness.',
    lookFor: 'A small subject surrounded by lots of simple, uncluttered space.',
    phrase: 'with generous negative space, the small subject surrounded by a wide expanse of empty, uncluttered space',
    keywords: 'negative space, minimalist, small subject, empty background',
    videoPhrase: 'minimalist framing with lots of empty space around the subject',
    tip: 'Use for loneliness, calm, or minimalism, and to leave room for text on posters and thumbnails.',
    insight: 'Empty space is not wasted space. It makes the subject stand out and gives the image a quiet, breathing feel.',
    exampleQuery: 'negative space minimalist photography',
  },
  {
    id: 'comp-symmetry',
    name: 'Symmetry & Centered Framing',
    category: 'composition',
    level: 'fundamental',
    definition: 'Placing the subject dead-center, with the left and right halves of the frame mirroring each other.',
    lookFor: 'A balanced, formal image where one half reflects the other: corridors, facades, reflections.',
    phrase: 'in a perfectly symmetrical, centered composition, the subject in the middle with the scene mirrored on both sides',
    keywords: 'symmetrical composition, centered, one-point perspective',
    videoPhrase: 'perfectly centered, symmetrical framing',
    tip: 'Use for architecture, reflections, and deliberate, stylized looks (think Wes Anderson). It breaks the rule of thirds on purpose.',
    insight: 'Symmetry feels orderly and intentional. A single element that breaks the symmetry becomes a strong focal point.',
    exampleQuery: 'symmetrical composition photography',
  },
  {
    id: 'comp-frame-within-frame',
    name: 'Frame Within a Frame',
    category: 'composition',
    level: 'intermediate',
    definition: 'Using something in the scene, such as a doorway, window, arch, or branches, to surround the subject.',
    lookFor: 'A darker border shape in the foreground that encloses the subject.',
    phrase: 'framed through a doorway or window in the foreground, the subject seen inside that natural frame',
    keywords: 'frame within a frame, doorway framing, natural frame',
    videoPhrase: 'subject framed through a doorway',
    tip: 'Name the framing object. It adds depth and makes the viewer feel like they are looking in.',
    insight: 'The inner frame isolates the subject and adds a foreground layer, which makes the image feel three-dimensional.',
    exampleQuery: 'frame within a frame photography',
  },
  {
    id: 'comp-foreground-layers',
    name: 'Foreground Layers (Depth)',
    category: 'composition',
    level: 'intermediate',
    definition: 'Building the image in layers: something in the foreground, the subject in the middle ground, and a background behind.',
    lookFor: 'A blurry or dark object close to the lens, the sharp subject behind it, and a distant background.',
    phrase: 'with layered depth: an out-of-focus object close to the lens in the foreground, the subject sharp in the middle ground, and the background receding behind',
    keywords: 'foreground interest, layered depth, blurred foreground',
    videoPhrase: 'foreground elements passing close to the lens',
    tip: 'Describe all three layers. It is one of the most reliable ways to make generated images look like real photographs.',
    insight: 'Flat images usually have everything at one distance. Overlapping layers are one of the strongest cues our brains use to read depth.',
    exampleQuery: 'foreground interest layered landscape photography',
  },

  // ---------------- Shot size ----------------
  {
    id: 'framing-extreme-wide',
    name: 'Extreme Wide Shot (Establishing Shot)',
    category: 'framing',
    level: 'fundamental',
    definition: 'A very wide view of a location in which people, if present, appear tiny.',
    lookFor: 'The environment fills the frame; the subject is a small detail within it.',
    phrase: 'an extreme wide establishing shot in which the subject is tiny against the vast surroundings',
    keywords: 'extreme wide shot, establishing shot, vast landscape, tiny figure',
    videoPhrase: 'extreme wide establishing shot',
    tip: 'Use to show scale and place. Give the viewer one small human-sized element so the size of everything else reads.',
    insight: 'Films often open scenes with one to answer "where are we?" before cutting closer to the people.',
    exampleQuery: 'extreme wide shot tiny person landscape',
  },
  {
    id: 'framing-full-shot',
    name: 'Full Shot (Wide Shot)',
    category: 'framing',
    level: 'fundamental',
    definition: 'Shows the whole person from head to toe, with some surroundings.',
    lookFor: 'The complete figure, including feet, with a little space above and below.',
    phrase: 'a full shot showing the subject from head to toe within their surroundings',
    keywords: 'full body shot, head to toe',
    videoPhrase: 'full shot, head to toe',
    tip: 'Use for outfits, poses, dance, and action where the whole body matters.',
    insight: 'Cutting the frame at the ankles tends to look like a mistake; either include the feet or crop clearly higher.',
    exampleQuery: 'full body shot photography',
  },
  {
    id: 'framing-cowboy-american',
    name: 'Cowboy Shot (American Shot)',
    category: 'framing',
    level: 'intermediate',
    definition: 'Frames a person from about mid-thigh up. It comes from Westerns, where it kept both the face and the holstered gun in view.',
    lookFor: 'The frame cuts across the thighs, showing hands and hips as well as the face.',
    phrase: 'a cowboy shot framing the subject from mid-thigh up, hands visible near the hips',
    keywords: 'cowboy shot, mid-thigh framing',
    videoPhrase: 'cowboy shot, framed from mid-thigh up',
    tip: 'Use for confident character poses where you want to see hands, belts, or props along with expression.',
    insight: 'French critics called it the "plan américain" (American shot) because it was so common in Hollywood Westerns.',
    exampleQuery: 'cowboy shot framing western',
  },
  {
    id: 'framing-medium-shot',
    name: 'Medium Shot',
    category: 'framing',
    level: 'fundamental',
    definition: 'Frames a person from about the waist up.',
    lookFor: 'Face, gestures, and upper body, with some background visible.',
    phrase: 'a medium shot framing the subject from the waist up',
    keywords: 'medium shot, waist-up',
    videoPhrase: 'medium shot, waist up',
    tip: 'The everyday storytelling shot. Good for conversations and for showing both expression and body language.',
    insight: 'It roughly matches the distance at which we talk to someone, so it feels natural and neutral.',
    exampleQuery: 'medium shot waist up portrait',
  },
  {
    id: 'framing-closeup',
    name: 'Close-Up',
    category: 'framing',
    level: 'fundamental',
    definition: 'Frames the face (or one object) so it fills most of the picture, usually from the shoulders or chin up.',
    lookFor: 'The face fills the frame; background is minimal.',
    phrase: 'a close-up on the face, filling the frame from the chin to the top of the head',
    keywords: 'close-up portrait, face fills frame',
    videoPhrase: 'close-up on the face',
    tip: 'Use when emotion is the point. Combine with a portrait lens and shallow depth of field.',
    insight: 'Close-ups remove context so the viewer reads only the expression. In films they are saved for emotional beats.',
    exampleQuery: 'close up portrait photography',
  },
  {
    id: 'framing-extreme-closeup',
    name: 'Extreme Close-Up',
    category: 'framing',
    level: 'intermediate',
    definition: 'A very tight crop on a small detail: just the eyes, lips, hands, or a single object.',
    lookFor: 'One detail fills the whole frame, often with visible texture.',
    phrase: 'an extreme close-up of the eyes, showing skin texture and reflections in the iris',
    keywords: 'extreme close-up, eyes, fine texture',
    videoPhrase: 'extreme close-up on the eyes',
    tip: 'Describe what is reflected or visible in the detail (city lights in the eyes, sweat on the brow) for realism.',
    insight: 'Removing everything except one detail creates intensity, and sometimes discomfort, which thrillers use deliberately.',
    exampleQuery: 'extreme close up eye photography',
  },

  // ---------------- Camera angle ----------------
  {
    id: 'angle-eye-level',
    name: 'Eye Level',
    category: 'angles',
    level: 'fundamental',
    definition: 'The camera sits at the subject\'s eye height, looking straight at them.',
    lookFor: 'A neutral view; the horizon sits level with the subject\'s eyes.',
    phrase: 'shot at eye level',
    keywords: 'eye level',
    videoPhrase: 'camera at eye level',
    tip: 'The neutral default. Use it when you want the viewer to feel like an equal to the subject.',
    insight: 'Because it is neutral, any other angle reads as a choice. That is why low and high angles feel expressive.',
    exampleQuery: 'eye level portrait photography',
  },
  {
    id: 'angle-low-hero',
    name: 'Low Angle (Hero Shot)',
    category: 'angles',
    level: 'fundamental',
    definition: 'The camera is below the subject\'s eye level, looking up.',
    lookFor: 'The subject towers over the viewer; you see more sky or ceiling behind them.',
    phrase: 'shot from a low angle looking up, so the subject towers over the viewer',
    keywords: 'low angle, looking up, towering',
    videoPhrase: 'low-angle shot looking up at the subject',
    tip: 'Use for power, heroism, or menace. A wide lens close to the ground exaggerates the effect.',
    insight: 'We look up at things that are bigger or more powerful than us, so the angle borrows that feeling.',
    exampleQuery: 'low angle shot looking up person',
  },
  {
    id: 'angle-high-bird',
    name: 'High Angle / Bird\'s-Eye View',
    category: 'angles',
    level: 'fundamental',
    definition: 'A high angle looks down at the subject; a bird\'s-eye (overhead) view looks straight down from above.',
    lookFor: 'The subject looks smaller; from directly overhead, the scene turns into patterns and shapes.',
    phrase: 'seen from a high angle looking down, making the subject appear small',
    keywords: 'high angle, looking down, bird\'s-eye view',
    videoPhrase: 'overhead bird\'s-eye view looking straight down',
    tip: 'Use for vulnerability or isolation, and straight overhead for maps, flat lays, and crowds.',
    insight: 'Looking down on someone makes them seem smaller and weaker. Straight overhead removes perspective entirely, so shapes read graphically.',
    exampleQuery: 'bird\'s eye view photography overhead',
  },
  {
    id: 'angle-over-the-shoulder',
    name: 'Over-the-Shoulder',
    category: 'angles',
    level: 'intermediate',
    definition: 'Shot from behind one person, over their shoulder, looking at someone or something they face.',
    lookFor: 'A blurred shoulder and head in the foreground on one side, the sharp subject beyond.',
    phrase: 'an over-the-shoulder shot from just behind the subject, their blurred shoulder in the foreground framing what they are looking at',
    keywords: 'over-the-shoulder shot, foreground shoulder',
    videoPhrase: 'over-the-shoulder shot from just behind the subject',
    tip: 'Use for conversations and confrontations. It puts the viewer inside the scene.',
    insight: 'The foreground shoulder adds a layer of depth and ties the two characters together in space.',
    exampleQuery: 'over the shoulder shot film',
  },
  {
    id: 'angle-dutch',
    name: 'Dutch Angle (Canted Angle)',
    category: 'angles',
    level: 'intermediate',
    definition: 'The camera is tilted sideways so the horizon runs diagonally.',
    lookFor: 'Verticals and the horizon are slanted, making the frame feel off-balance.',
    phrase: 'shot at a Dutch angle, the camera tilted so the horizon runs diagonally across the frame',
    keywords: 'dutch angle, tilted camera, diagonal horizon',
    videoPhrase: 'tilted Dutch angle',
    tip: 'Use sparingly for unease, madness, or chaos. A small tilt (10–20°) reads as deliberate; too much looks like a mistake.',
    insight: '"Dutch" is thought to come from "Deutsch" (German): the angle was popular in German Expressionist films of the 1920s.',
    exampleQuery: 'dutch angle shot tilted',
  },

  // ---------------- Lenses ----------------
  {
    id: 'lens-standard-50mm',
    name: '50mm Standard Lens',
    category: 'lenses',
    level: 'fundamental',
    definition: 'A "normal" focal length on a full-frame camera, with a view similar to how we see a scene naturally.',
    lookFor: 'Natural-looking perspective with no obvious stretching or flattening.',
    phrase: 'shot on a 50mm lens with natural, true-to-life perspective',
    keywords: '50mm lens, natural perspective',
    videoPhrase: 'shot on a 50mm lens',
    tip: 'A safe, realistic default for street, documentary, and everyday scenes.',
    insight: 'Its view is close to our own field of attention, which is why 50mm images feel honest and unexaggerated.',
    exampleQuery: '50mm street photography',
  },
  {
    id: 'lens-wide-14mm',
    name: 'Wide-Angle Lens (14–24mm)',
    category: 'lenses',
    level: 'fundamental',
    definition: 'A short focal length that shows a very wide view.',
    lookFor: 'A lot of the scene in frame, exaggerated depth (near things look big, far things tiny), and lines that bend or lean near the edges.',
    phrase: 'shot on a 14mm ultra-wide lens, exaggerating the depth so the foreground looms and the background stretches away',
    keywords: '14mm ultra-wide lens, exaggerated perspective',
    videoPhrase: 'ultra-wide 14mm lens with exaggerated depth',
    tip: 'Use for architecture, landscapes, and cramped interiors. Get close to a foreground object for drama; avoid it for flattering faces.',
    insight: 'The lens itself does not change perspective; standing close does. A wide lens lets you stand close and still fit everything in, which is where the exaggerated look comes from.',
    exampleQuery: 'ultra wide angle 14mm photography',
  },
  {
    id: 'lens-portrait-85mm',
    name: '85mm Portrait Lens',
    category: 'lenses',
    level: 'fundamental',
    definition: 'A moderate telephoto focal length, a classic choice for head-and-shoulders portraits.',
    lookFor: 'Natural facial proportions and, at wide apertures like f/1.4–f/2, a softly blurred background.',
    phrase: 'shot on an 85mm portrait lens at f/1.8, the face sharp and the background melting into soft blur',
    keywords: '85mm portrait lens, f/1.8, soft background blur',
    videoPhrase: '85mm lens with shallow focus on the face',
    tip: 'The go-to for portraits. Pair with a wide aperture to separate the subject from the background.',
    insight: 'Faces look natural because you stand a comfortable distance back; shooting close with a wide lens makes noses look bigger.',
    exampleQuery: '85mm portrait bokeh',
  },
  {
    id: 'lens-telephoto-200mm',
    name: 'Telephoto Lens (200mm)',
    category: 'lenses',
    level: 'intermediate',
    definition: 'A long focal length that magnifies distant subjects and shows a narrow slice of the scene.',
    lookFor: '"Compression": the background looks larger and closer to the subject, and depth looks flattened.',
    phrase: 'shot from far away on a 200mm telephoto lens, compressing the scene so the huge background looms right behind the subject',
    keywords: '200mm telephoto, compressed background',
    videoPhrase: 'long 200mm telephoto shot with a compressed background',
    tip: 'Use to put a giant moon, sun, or mountain right behind a subject, and for wildlife and sports.',
    insight: 'Compression comes from the camera being far away, not from the lens itself. The long lens just lets you fill the frame from that distance.',
    exampleQuery: 'telephoto compression moon photography',
  },
  {
    id: 'lens-macro-100mm',
    name: 'Macro Lens (100mm)',
    category: 'lenses',
    level: 'intermediate',
    definition: 'A lens that can focus extremely close, showing small subjects at life size (1:1) or larger.',
    lookFor: 'Tiny details filling the frame and an extremely thin slice of focus.',
    phrase: 'a macro photograph taken with a 100mm macro lens, the tiny subject filling the frame with only a razor-thin slice in focus',
    keywords: 'macro photography, 100mm macro, extreme detail, razor-thin focus',
    videoPhrase: 'macro shot with razor-thin focus',
    tip: 'Use for insects, droplets, eyes, jewellery, and textures. Mention what is in focus and what blurs.',
    insight: 'Depth of field shrinks as you focus closer, so macro focus can be millimetres deep. Real macro photographers often stack several shots.',
    exampleQuery: 'macro photography water droplet',
  },
  {
    id: 'lens-anamorphic',
    name: 'Anamorphic Lens',
    category: 'lenses',
    level: 'advanced',
    definition: 'A cinema lens that squeezes a wide image horizontally onto the sensor; it is unsqueezed later into a widescreen frame (about 2.39:1).',
    lookFor: 'Oval-shaped (vertically stretched) background blur, long horizontal lens flares, and a very wide frame.',
    phrase: 'shot on an anamorphic lens, with long horizontal lens flares and oval background bokeh',
    keywords: 'anamorphic lens, horizontal lens flare, oval bokeh',
    videoPhrase: 'anamorphic lens with horizontal flares across the frame',
    tip: 'Use for a big-screen cinema feel, especially at night with bright lights that can flare.',
    insight: 'Anamorphic lenses let films get a widescreen picture onto standard 35mm film. Their flares and oval bokeh became a signature of the cinema look.',
    exampleQuery: 'anamorphic lens flare night',
  },

  // ---------------- Exposure & focus ----------------
  {
    id: 'exp-aperture',
    name: 'Aperture & Depth of Field',
    category: 'exposure',
    level: 'fundamental',
    definition: 'Aperture is the opening in the lens, written as an f-number. Small f-numbers (f/1.4, f/2) are wide openings; big ones (f/11, f/16) are small openings.',
    lookFor: 'At f/1.4–f/2.8 only the subject is sharp and the background blurs (shallow depth of field). At f/8–f/16 most of the scene is sharp (deep depth of field).',
    phrase: 'at a wide f/1.8 aperture, so only the subject is sharp and the background dissolves into soft bokeh',
    keywords: 'f/1.8, shallow depth of field, bokeh',
    videoPhrase: 'shallow depth of field, background softly out of focus',
    tip: 'Say "shallow depth of field" to isolate a subject, or "deep focus, everything sharp" for landscapes and group shots.',
    insight: 'Depth of field depends on three things together: aperture, focal length, and distance to the subject. Wide aperture, long lens, and close subject all make it shallower.',
    exampleQuery: 'shallow depth of field bokeh portrait',
  },
  {
    id: 'exp-shutter',
    name: 'Shutter Speed',
    category: 'exposure',
    level: 'fundamental',
    definition: 'How long the shutter stays open, from 1/4000 of a second to several seconds.',
    lookFor: 'Fast shutter (1/1000s) freezes motion: splashes and athletes are crisp. Slow shutter (1/15s and longer) turns movement into blur.',
    phrase: 'frozen with a fast 1/2000s shutter speed, so fast motion is crisp and sharp in mid-air',
    keywords: 'fast shutter speed, frozen motion',
    videoPhrase: 'natural motion blur on moving objects',
    tip: 'Choose freeze ("frozen mid-air") or blur ("motion-blurred crowd, sharp subject") depending on the energy you want.',
    insight: 'Each halving of shutter time halves the light. Photographers trade shutter speed against aperture and ISO to keep brightness the same.',
    exampleQuery: 'fast shutter speed frozen splash',
  },
  {
    id: 'exp-long-exposure',
    name: 'Long Exposure',
    category: 'exposure',
    level: 'intermediate',
    definition: 'A shutter left open for seconds or minutes, usually on a tripod.',
    lookFor: 'Silky water, streaked clouds, light trails from cars, while still things stay sharp.',
    phrase: 'a long exposure on a tripod, turning moving water and clouds into silky blur while still objects stay sharp',
    keywords: 'long exposure, silky water, light trails',
    videoPhrase: 'time-lapse with long-exposure light trails',
    tip: 'Great for waterfalls, seascapes, and night traffic. Mention what stays sharp so the image does not look like camera shake.',
    insight: 'Anything that moves blurs and anything still stays sharp, which is why long exposures feel calm and dreamlike.',
    exampleQuery: 'long exposure silky water',
  },
  {
    id: 'exp-iso',
    name: 'ISO & Grain',
    category: 'exposure',
    level: 'fundamental',
    definition: 'ISO is how strongly the camera amplifies light. Low ISO (100) is clean; high ISO (3200+) brightens dark scenes but adds grain/noise.',
    lookFor: 'Low ISO: smooth, clean tones. High ISO: visible speckled grain, especially in shadows.',
    phrase: 'shot at high ISO, with visible fine grain in the shadows',
    keywords: 'high ISO, film grain, low light',
    videoPhrase: 'grainy low-light footage',
    tip: 'Ask for "clean, low ISO" for crisp commercial images, or "high ISO grain" for gritty night and documentary feel.',
    insight: 'Aperture, shutter speed, and ISO together are the "exposure triangle": change one and you must adjust another to keep the same brightness.',
    exampleQuery: 'high ISO grain night street photography',
  },

  // ---------------- Color & film ----------------
  {
    id: 'color-temperature',
    name: 'Color Temperature (Warm vs Cool)',
    category: 'color-film',
    level: 'fundamental',
    definition: 'How orange or blue light looks, measured in kelvin: candles about 1900K, tungsten bulbs about 3200K, daylight about 5600K, shade about 7000K+.',
    lookFor: 'Warm scenes lean orange and yellow; cool scenes lean blue and teal.',
    phrase: 'in warm, tungsten-toned light with amber highlights',
    keywords: 'warm color temperature, amber tones',
    videoPhrase: 'warm amber color temperature',
    tip: 'Warm feels cozy, nostalgic, or romantic; cool feels calm, lonely, clinical, or cold. Mixing both creates contrast.',
    insight: 'Confusingly, "warmer" colors have a lower kelvin number. The scale comes from the color of heated metal.',
    exampleQuery: 'warm vs cool color temperature photography',
  },
  {
    id: 'color-teal-orange',
    name: 'Teal & Orange Grade',
    category: 'color-film',
    level: 'intermediate',
    definition: 'A popular blockbuster color grade that pushes shadows and backgrounds toward teal while keeping skin tones warm orange.',
    lookFor: 'Blue-green shadows and backgrounds with warm, glowing faces.',
    phrase: 'with a teal-and-orange color grade, cool teal shadows and warm orange skin tones',
    keywords: 'teal and orange color grade, blockbuster look',
    videoPhrase: 'teal-and-orange blockbuster color grade',
    tip: 'A quick route to a big-budget action look. Overused, it can look generic, so keep it subtle for realism.',
    insight: 'Skin tones sit in the orange range, and teal is roughly its opposite on the color wheel, so the grade makes people pop from their surroundings.',
    exampleQuery: 'teal and orange color grading film',
  },
  {
    id: 'color-kodachrome-vintage',
    name: 'Kodachrome Film Look',
    category: 'color-film',
    level: 'advanced',
    definition: 'Kodachrome was a color slide film (1935–2009) known for rich reds and yellows, deep blues, strong contrast, and fine grain.',
    lookFor: 'Saturated but natural colors, warm reds, deep shadows, and a mid-century feel.',
    phrase: 'with the look of vintage Kodachrome slide film: rich reds and yellows, deep blues, and fine grain',
    keywords: 'Kodachrome film look, vintage 1960s color, fine grain',
    videoPhrase: 'vintage Kodachrome-style color',
    tip: 'Use for nostalgic, mid-century scenes: road trips, diners, street life from the 1950s–70s.',
    insight: 'Unlike most color films, Kodachrome had no color dyes in the film itself; they were added during a complex development process (K-14), which only a few labs could run.',
    exampleQuery: 'Kodachrome photography 1960s',
  },
  {
    id: 'color-cinestill-800t',
    name: 'CineStill 800T Film Look',
    category: 'color-film',
    level: 'advanced',
    definition: 'A tungsten-balanced color film adapted from Kodak motion-picture stock, loved for night photography.',
    lookFor: 'Red-orange glowing halos (halation) around bright lights, and cool cyan-teal tones overall.',
    phrase: 'with the look of CineStill 800T film: glowing red halation around bright lights and cool teal tones',
    keywords: 'CineStill 800T, red halation, cool night tones',
    videoPhrase: 'CineStill-style night look with red halation around lights',
    tip: 'Best for neon, rainy streets, and night city scenes where bright lights can create halos.',
    insight: 'The motion-picture film has a backing layer (remjet) that stops light bouncing back through it. CineStill removes that layer, so bright lights reflect back and create the red glow.',
    exampleQuery: 'CineStill 800T halation night',
  },
  {
    id: 'color-film-noir-blackwhite',
    name: 'Film Noir Black & White',
    category: 'color-film',
    level: 'intermediate',
    definition: 'The high-contrast black-and-white style of 1940s–50s crime films.',
    lookFor: 'Deep blacks, bright highlights, hard shadows (often striped by window blinds), rain-slick streets, and smoke.',
    phrase: 'in high-contrast black and white film noir style, with hard shadows from venetian blinds striping the scene',
    keywords: 'film noir, black and white, high contrast, venetian blind shadows',
    videoPhrase: 'high-contrast black-and-white noir look',
    tip: 'Combine with hard light and low-key lighting. Details like blinds, smoke, and wet streets sell the look.',
    insight: '"Noir" means "black" in French, a label French critics gave these films. The look borrows heavily from German Expressionist cinema.',
    exampleQuery: 'film noir still venetian blind shadows',
  },

  // ---------------- Movement (video) ----------------
  {
    id: 'move-static',
    name: 'Static Shot (Locked-Off)',
    category: 'movements',
    level: 'fundamental',
    definition: 'The camera does not move at all; only the subject moves within the frame.',
    lookFor: 'A fixed frame, like a photograph that comes to life.',
    phrase: 'a static shot on a tripod',
    keywords: 'static locked-off camera',
    videoPhrase: 'static locked-off shot on a tripod, the camera does not move',
    tip: 'Use when the action itself should carry the shot, or for calm, observational moments.',
    insight: 'Video models often add camera drift on their own; saying "static, locked-off camera" keeps it still.',
    exampleQuery: 'static shot cinematography',
  },
  {
    id: 'move-pan-tilt',
    name: 'Pan & Tilt',
    category: 'movements',
    level: 'fundamental',
    definition: 'The camera stays in place and rotates: left or right is a pan, up or down is a tilt.',
    lookFor: 'The view sweeps across or up a scene while the camera position stays fixed.',
    phrase: 'a slow pan across the scene',
    keywords: 'slow pan',
    videoPhrase: 'the camera slowly pans left to right across the scene',
    tip: 'Use to reveal a wide scene gradually or follow a subject moving past. Say the direction and speed.',
    insight: 'Because the camera does not travel, a pan shows no parallax; nearby and faraway objects shift together.',
    exampleQuery: 'camera pan shot',
  },
  {
    id: 'move-handheld',
    name: 'Handheld',
    category: 'movements',
    level: 'intermediate',
    definition: 'The camera is held by an operator without stabilisation, so it moves slightly with their body.',
    lookFor: 'Small natural shakes and drift, like documentary or news footage.',
    phrase: 'a handheld shot',
    keywords: 'handheld camera',
    videoPhrase: 'handheld camera with subtle natural shake, documentary style',
    tip: 'Use for urgency, realism, and intimacy. Ask for "subtle" shake unless you want chaos.',
    insight: 'The slight movement reminds viewers there is a person holding the camera, which feels immediate and real.',
    exampleQuery: 'handheld camera documentary style',
  },
  {
    id: 'movement-steadicam-tracking',
    name: 'Tracking Shot (Steadicam)',
    category: 'movements',
    level: 'intermediate',
    definition: 'The camera travels alongside, behind, or ahead of a moving subject, smoothly stabilised.',
    lookFor: 'The subject stays in roughly the same place in frame while the world slides past.',
    phrase: 'a smooth tracking shot following the subject',
    keywords: 'tracking shot, steadicam',
    videoPhrase: 'smooth Steadicam tracking shot following closely behind the subject as they walk',
    tip: 'Use for walking scenes and long continuous takes. Say whether the camera leads, follows, or moves alongside.',
    insight: 'Garrett Brown\'s Steadicam (1970s) isolates the camera from the operator\'s steps using a sprung arm and a weighted rig.',
    exampleQuery: 'steadicam tracking shot',
  },
  {
    id: 'movement-crane-jib-reveal',
    name: 'Crane Shot (Reveal)',
    category: 'movements',
    level: 'intermediate',
    definition: 'The camera rises or descends on a crane or jib arm, often lifting over an obstacle to reveal a larger scene.',
    lookFor: 'The camera climbs, and the view opens up from a close detail to a wide vista.',
    phrase: 'a rising crane shot',
    keywords: 'crane shot, rising reveal',
    videoPhrase: 'the camera starts low on a small detail, then rises smoothly on a crane to reveal the vast landscape',
    tip: 'Use to open or close a scene. Describe where the shot starts and what it reveals.',
    insight: 'Moving from a human-scale detail to a grand overview lifts the emotional scale, which is why it is common at the start or end of films.',
    exampleQuery: 'crane shot reveal cinematography',
  },
  {
    id: 'movement-dolly-zoom',
    name: 'Dolly Zoom (Vertigo Effect)',
    category: 'movements',
    level: 'advanced',
    definition: 'The camera moves toward or away from the subject while zooming the opposite way, so the subject stays the same size.',
    lookFor: 'The subject holds still in frame while the background seems to stretch away or rush forward.',
    phrase: 'a dolly zoom',
    keywords: 'dolly zoom, vertigo effect',
    videoPhrase: 'dolly zoom: the camera pulls back while zooming in, the character stays the same size as the background warps forward behind them',
    tip: 'Use for a shocking realisation or dizziness. Only meaningful in video; a still image can\'t show it.',
    insight: 'Credited to cameraman Irmin Roberts and made famous by Hitchcock\'s "Vertigo" (1958). It works because perspective changes with distance while the zoom hides the size change.',
    exampleQuery: 'dolly zoom vertigo effect',
  },
];

export const TERM_BY_ID: Record<string, PhotoTerm> = Object.fromEntries(PHOTOGRAPHY_TERMS.map((t) => [t.id, t]));

export const termsInCategory = (category: CategoryId) => PHOTOGRAPHY_TERMS.filter((t) => t.category === category);

export const CAMERA_PRESETS = [
  { id: 'digital-cinema', label: 'Digital cinema camera (ARRI Alexa)', phrase: 'shot on an ARRI Alexa digital cinema camera', medium: 'digital' },
  { id: 'medium-format', label: 'Medium-format stills camera', phrase: 'shot on a medium-format camera with very fine detail', medium: 'digital' },
  { id: 'film-35mm', label: '35mm film camera', phrase: 'shot on 35mm film', medium: 'film' },
  { id: 'film-70mm', label: '70mm large-format film (IMAX)', phrase: 'shot on 70mm large-format film', medium: 'film' },
  { id: 'phone', label: 'Smartphone', phrase: 'shot on a smartphone', medium: 'digital' },
] as const;

export const ASPECT_RATIOS = [
  { value: '16:9', label: '16:9 widescreen', words: 'wide 16:9 frame', mj: '16:9' },
  { value: '2.39:1', label: '2.39:1 cinema scope', words: 'very wide 2.39:1 cinemascope frame', mj: '239:100' },
  { value: '3:2', label: '3:2 classic photo', words: '3:2 landscape frame', mj: '3:2' },
  { value: '4:5', label: '4:5 portrait (Instagram)', words: 'vertical 4:5 frame', mj: '4:5' },
  { value: '9:16', label: '9:16 vertical video', words: 'tall vertical 9:16 frame', mj: '9:16' },
  { value: '1:1', label: '1:1 square', words: 'square 1:1 frame', mj: '1:1' },
] as const;

// Plain-language briefs: they describe the look, not the vocabulary. The terms are revealed after grading.
export const CHALLENGES: Challenge[] = [
  {
    id: 'chal-window-portrait',
    title: 'Portrait by the window',
    level: 'fundamental',
    kind: 'image',
    focus: 'Light & lens',
    brief: 'A woman reads a letter beside a large window on a cloudy afternoon. Light comes from one side only, so half her face is bright and the other half fades gently into shadow with no harsh edges. She is framed from the chest up, sharp, while the room behind her melts into a smooth blur. The mood is quiet and warm.',
    answerTermIds: ['light-side-window', 'light-soft', 'lens-portrait-85mm', 'exp-aperture', 'color-temperature'],
    sampleSolution: 'A close portrait of a woman reading a letter beside a large window on an overcast afternoon. Soft window light falls from the left, so the left side of her face is bright and the right side fades gently into shadow. Shot on an 85mm lens at f/1.8: her eyes are sharp and the room behind her dissolves into soft blur. Warm, muted tones and a quiet, intimate mood.',
  },
  {
    id: 'chal-lonely-beach',
    title: 'Alone on the shore',
    level: 'fundamental',
    kind: 'image',
    focus: 'Composition',
    brief: 'A single small figure walks along an enormous, empty beach at dusk. The person is tiny and placed well off to one side, with the horizon low in the frame so most of the picture is plain, pale sky. It should feel calm and lonely.',
    answerTermIds: ['comp-negative-space', 'comp-rule-of-thirds', 'framing-extreme-wide', 'light-blue-hour'],
    sampleSolution: 'An extreme wide shot of a single tiny figure walking along a vast, empty beach at blue hour. The figure sits on the right third of the frame and the horizon on the lower third, leaving generous negative space of pale, empty sky above. Soft twilight, calm and lonely.',
  },
  {
    id: 'chal-boxer',
    title: 'Boxer between rounds',
    level: 'intermediate',
    kind: 'image',
    focus: 'Lighting',
    brief: 'A boxer sits on a wooden stool in a dusty locker room. The only light comes from behind him, drawing a bright edge along his shoulders and arms, while his face and the room stay mostly in darkness. Dust hangs in the air. Frame him from the waist up with the background thrown out of focus.',
    answerTermIds: ['lighting-rim-edge', 'lighting-lowkey', 'framing-medium-shot', 'exp-aperture'],
    sampleSolution: 'A medium shot of a boxer sitting on a wooden stool in a dusty locker room. Low-key lighting: a single strong rim light from behind traces a bright outline along his shoulders and arms while his face stays mostly in shadow. Dust particles glow in the backlight. Shallow depth of field blurs the lockers behind him.',
  },
  {
    id: 'chal-rooftop-hero',
    title: 'Rooftop hero',
    level: 'intermediate',
    kind: 'image',
    focus: 'Angle & lens',
    brief: 'A courier stands on the edge of a rooftop at sunset. We are down near their boots looking up, so they tower over us against a huge sky, and the building edge stretches dramatically toward the camera. Warm, low sun catches their side. Show them from head to toe.',
    answerTermIds: ['angle-low-hero', 'lens-wide-14mm', 'light-golden-hour', 'framing-full-shot'],
    sampleSolution: 'A full shot of a bike courier standing on the edge of a city rooftop at golden hour, shot from a low angle near their boots looking up so they tower against a vast orange sky. A 14mm ultra-wide lens exaggerates the depth: the rooftop edge stretches toward the camera. Warm low sunlight rakes across their side.',
  },
  {
    id: 'chal-neon-alley',
    title: 'Neon alley at night',
    level: 'advanced',
    kind: 'image',
    focus: 'Color & film look',
    brief: 'A rain-soaked alley in Tokyo at night, lined with glowing ramen signs. Every bright sign has a soft red-orange glow bleeding around it, and the shadows are cool teal. The frame is extremely wide like a cinema screen, with long horizontal streaks of flare from the brightest lights. The alley walls draw your eye toward a figure with an umbrella in the distance.',
    answerTermIds: ['color-cinestill-800t', 'lens-anamorphic', 'comp-leading-lines'],
    sampleSolution: 'A rain-slicked Tokyo alley at night lined with glowing ramen signs, the walls converging as leading lines toward a distant figure with an umbrella. Shot on an anamorphic lens in a wide 2.39:1 frame with long horizontal flares from the brightest signs. The look of CineStill 800T film: red halation glowing around every light, cool teal shadows, reflections in the puddles.',
  },
  {
    id: 'chal-mountain-reveal',
    title: 'Mountain reveal (video)',
    level: 'advanced',
    kind: 'video',
    focus: 'Camera movement',
    brief: 'A video shot that begins very close on a tiny frozen flower on a ridge. The camera then rises smoothly into the air, and as it climbs we discover a lone traveler looking up at a colossal cathedral carved into a snowy mountain face, now tiny in a vast view.',
    answerTermIds: ['movement-crane-jib-reveal', 'framing-extreme-wide', 'lens-wide-14mm'],
    sampleSolution: 'The shot opens in extreme close-up on a small frozen flower on a mountain ridge. The camera then rises smoothly in a crane shot, climbing high to reveal an extreme wide view: a lone traveler, tiny in frame, looking up at a colossal Gothic cathedral carved into a snowy peak. Ultra-wide lens, drifting mist, slow and majestic pacing.',
  },
];

export const CHALLENGE_BY_ID: Record<string, Challenge> = Object.fromEntries(CHALLENGES.map((c) => [c.id, c]));
